chat_model:
    # google: gemini-2.5-flash-lite
    google: gemini-2.5-flash
    # google: gemini-2.0-flash
    ollama: llama3.2

embedding_model:
    google: text-embedding-005
    #google: text-multilingual-embedding-002
    ollama: mxbai-embed-large
